services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - crypto-dev

  cryptoquant_init:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - BUILD_TAGS=init
    container_name: cryptoquant_init
    depends_on:
      redis:
        condition: service_healthy
    restart: "no"
    env_file:
      - .env
    networks:
      - crypto-dev

  xrp:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - BUILD_TAGS=server
    container_name: cryptoquant_xrp_dev
    depends_on:
      redis:
        condition: service_healthy
      cryptoquant_init:
        condition: service_completed_successfully
    restart: unless-stopped
    labels:
      engine: xrp
      type: trader
    env_file:
      - .env
    environment:
      - ENGINE_NAME=xrp
      - USERNAME=${USERNAME:-postgres}
      - PASSWORD=${PASSWORD:-postgres}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_NAME=${PG_NAME:-cryptoquant}
      - TS_HOST=${TS_HOST}
      - TS_PORT=${TS_PORT}
      - TS_NAME=${TS_NAME:-cryptoquant_ts}
      - BINANCE_SYMBOL=XRPUSDT
      - UPBIT_SYMBOL=KRW-XRP
      - ANCHOR_SYMBOL=KRW-USDT
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - UPBIT_SECRET_KEY=${UPBIT_SECRET_KEY}
      - UPBIT_API_KEY=${UPBIT_API_KEY}
    volumes:
      - ./log/xrp:/app/log
      - .:/app
    networks:
      - crypto-dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  cow:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - BUILD_TAGS=server
    container_name: cryptoquant_cow_dev
    depends_on:
      redis:
        condition: service_healthy
      cryptoquant_init:
        condition: service_completed_successfully
    restart: unless-stopped
    labels:
      engine: cow
      type: trader
    env_file:
      - .env
    environment:
      - ENGINE_NAME=cow
      - USERNAME=${USERNAME:-postgres}
      - PASSWORD=${PASSWORD:-postgres}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_NAME=${PG_NAME:-cryptoquant}
      - TS_HOST=${TS_HOST}
      - TS_PORT=${TS_PORT}
      - TS_NAME=${TS_NAME:-cryptoquant_ts}
      - BINANCE_SYMBOL=COWUSDT
      - UPBIT_SYMBOL=KRW-COW
      - ANCHOR_SYMBOL=KRW-USDT
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - UPBIT_SECRET_KEY=${UPBIT_SECRET_KEY}
      - UPBIT_API_KEY=${UPBIT_API_KEY}
    volumes:
      - ./log/cow:/app/log
      - .:/app
    networks:
      - crypto-dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  redis_data:
  postgres_data:
  timescaledb_data:

networks:
  crypto-dev:
    external: true
    name: crypto-dev 