services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryptoquant
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_NAME=${PG_NAME}
      - TS_HOST=${TS_HOST}
      - TS_PORT=${TS_PORT}
      - TS_NAME=${TS_NAME}
      - BINANCE_SYMBOL=${BINANCE_SYMBOL}
      - UPBIT_SYMBOL=${UPBIT_SYMBOL}
      - ANCHOR_SYMBOL=${ANCHOR_SYMBOL}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
    volumes:
      - ./log:/app/log
    # Uncomment if you need to expose ports
    # ports:
    #   - "8080:8080" 
networks:
  shared:
    external: true
    name: crypto-bridge