x-base-engine: &base-engine
  # Base engine for all trading engines
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - BUILD_TAGS=server
  depends_on:
    redis:
      condition: service_healthy
    cryptoquant_init:
      condition: service_completed_successfully
  restart: unless-stopped
  networks:
    - crypto-bridge
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  deploy:
    resources:
      limits:
        cpus: '1.0'
        memory: 512M

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - 6379:6379
    networks:
      - crypto-bridge

  cryptoquant_init:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TAGS=init
    container_name: cryptoquant_init
    depends_on:
      redis:
        condition: service_healthy
    restart: "no"
    env_file:
      - .env
    networks:
      - crypto-bridge

  trader:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TAGS=trader
    container_name: trader
    depends_on:
      redis:
        condition: service_healthy
      cryptoquant_init:
        condition: service_completed_successfully
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - crypto-bridge
    volumes:
      - ./log/trader:/app/log
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  # Trading engines by each coin
  xrp:
    <<: *base-engine
    container_name: cryptoquant_xrp
    labels:
      engine: xrp
      type: trader
    env_file:
      - .env
    environment:
      - ENGINE_NAME=xrp
      - BINANCE_SYMBOL=XRPUSDT
      - UPBIT_SYMBOL=KRW-XRP
      - ANCHOR_SYMBOL=KRW-USDT
      - TRADER_ADDRESS=trader:50051
    volumes:
      - ./log/xrp:/app/log

  move:
    <<: *base-engine
    container_name: cryptoquant_move
    labels:
      engine: move
      type: trader
    env_file:
      - .env
    environment:
      - ENGINE_NAME=move
      - BINANCE_SYMBOL=MOVEUSDT
      - UPBIT_SYMBOL=KRW-MOVE
      - ANCHOR_SYMBOL=KRW-USDT
      - TRADER_ADDRESS=trader:50051
    volumes:
      - ./log/cow:/app/log

  cow:
    <<: *base-engine
    container_name: cryptoquant_cow
    labels:
      engine: cow
      type: trader
    env_file:
      - .env
    environment:
      - ENGINE_NAME=cow
      - BINANCE_SYMBOL=COWUSDT
      - UPBIT_SYMBOL=KRW-COW
      - ANCHOR_SYMBOL=KRW-USDT
      - TRADER_ADDRESS=trader:50051
    volumes:
      - ./log/cow:/app/log

networks:
  crypto-bridge:
    external: true
    name: crypto-bridge